[project]
name = "course-work-2"
version = "0.1.0"
description = ""
authors = [
    {name = "Evg Fomin",email = "efominykhgh@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests (>=2.32.5,<3.0.0)",
    "rich (>=14.2.0,<15.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.1,<10.0.0)",
    "black (>=25.11.0,<26.0.0)",
    "isort (>=7.0.0,<8.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "mypy (>=1.19.0,<2.0.0)",
    "pre-commit (>=4.5.0,<5.0.0)",
    "requests-mock (>=1.12.1,<2.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)"
]

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.5.0"
types-requests = "^2.32.4.20250913"

[tool.mypy]
    ignore_missing_imports = true